/**
 * Production runtime config — generated by CI from GitHub secrets.
 * Do not commit real keys. Copy to config.runtime.js for local prod testing.
 */
window.__JG_MART_SUPABASE__ = {
  url: 'https://xxxxxxxxxxxxx.supabase.co',
  anonKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...'
};
