name: Deploy to Production

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-catalog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm i -g vercel
      - run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ./src/web/catalog
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      - run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }} --yes
        working-directory: ./src/web/catalog
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}

  deploy-dashboard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm i -g vercel
      - run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ./src/web/dashboard
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      - run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }} --yes
        working-directory: ./src/web/dashboard
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
